language: perl
perl:
   - '5.18'
env:
   - BUILD=0
matrix:
   fast_finish: true
before_install:
   - 'if [[ $BUILD == 1 && ! -d .build/testing ]]; then unset BUILD; fi'
   - 'if [[ $BUILD == 0 ]]; then export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1; fi'
   - 'if [[ $BUILD == 0 ]]; then git clone git://github.com/ugexe/helpers; fi'
   - 'if [[ $BUILD == 0 ]]; then source helpers/init; fi'
   - 'if [[ $BUILD == 0 ]]; then build-perl; fi'
   - 'if [[ $BUILD == 0 ]]; then perl -V; fi'
   - 'if [[ $BUILD == 0 ]]; then git config --global user.name "TravisCI"; fi'
   - 'if [[ $BUILD == 0 ]]; then git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"; fi'
   - 'if [[ $BUILD == 1 ]]; then cd .build/testing; fi'
   - 'if [[ $BUILD == 1 ]]; then export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1; fi'
   - 'if [[ $BUILD == 1 ]]; then git clone git://github.com/ugexe/helpers; fi'
   - 'if [[ $BUILD == 1 ]]; then source helpers/init; fi'
   - 'if [[ $BUILD == 1 ]]; then build-perl; fi'
   - 'if [[ $BUILD == 1 ]]; then perl -V; fi'
   - 'if [[ $BUILD == 1 ]]; then export AUTHOR_TESTING=0; fi'
install:
   - 'if [[ $BUILD == 0 ]]; then cpan-install Dist::Zilla; fi'
   - "if [[ $BUILD == 0 ]]; then dzil authordeps --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 $HELPER_ROOT/bin/cpan-install; fi"
   - "if [[ $BUILD == 0 ]]; then dzil listdeps --author --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 $HELPER_ROOT/bin/cpan-install; fi"
   - 'if [[ $BUILD == 1 ]]; then cpan-install --deps; fi'
script:
   - 'if [[ $BUILD == 0 ]]; then dzil smoke --release --author; fi'
   - 'if [[ $BUILD == 1 && -f Makefile.PL ]]; then perl Makefile.PL && make test;    fi'
   - 'if [[ $BUILD == 1 && -f Build.PL    ]]; then perl Build.PL    && ./Build test; fi'
   - 'if [[ $BUILD == 1 && ! -f Makefile.PL && ! -f Build.PL ]]; then  make test;    fi'
notifications:
   email: false
